apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: shell-in-container
spec:
  kprobes:
  - call: "security_bprm_check"
    syscall: false
    args:
    - index: 0
      type: "linux_binprm"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "/bash"
        - "/sh"
        - "/zsh"
        - "/ash"
      matchNamespaces:
      - namespace: Pid
        operator: NotIn
        values:
        - "host_ns"
      matchActions:
      - action: Post
