apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: write-etc
spec:
  kprobes:
  - call: "security_file_open"
    syscall: false
    args:
    - index: 0
      type: "file"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc"
      matchActions:
      - action: Post
